language: python
python:
    - '2.7'
    - '3.5'
    - '3.6'
install:
    - pip install . # install package
    - pip install -r requirements.txt # install requires
    - pip install -r test/test_requirements.txt # install test requirements
script:
    - pytest --verbose
after_success:
    - coveralls
